name: Spider_Jun

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK
      uses: actions/setup-java@v3.11.0
      with:
        java-version: '18'
        distribution: 'temurin'
        
    - name: Clone project
      run: |
        rm -rf project
        rm -rf jar/custom_spider.jar
        git clone --recurse-submodules https://github.com/lh2513/Jun project
    - name: diy the app
      working-directory: ./project     
      run: |
         rm -rf app/src/main/java/com/github/catvod/spider/*
         curl -L https://github.com/lh2513/Jun/raw/master/app/src/main/java/com/github/catvod/spider/Init.java > app/src/main/java/com/github/catvod/spider/Init.java
         #curl -L https://github.com/lh2513/Jun/raw/master/app/src/main/java/com/github/catvod/spider/Proxy.java > app/src/main/java/com/github/catvod/spider/Proxy.java
         #curl -L https://github.com/lh2513/Jun/raw/master/app/src/main/java/com/github/catvod/spider/PushAgent.java > app/src/main/java/com/github/catvod/spider/PushAgent.java
         #添加AppYsV2
         curl -L https://github.com/lh2513/Jun/raw/master/app/src/main/java/com/github/catvod/spider/Kuaikan.java > app/src/main/java/com/github/catvod/spider/Kuaikan.java
         curl -L https://github.com/lh2513/Jun/raw/master/app/src/main/java/com/github/catvod/spider/Auete.java > app/src/main/java/com/github/catvod/spider/Auete.java
         curl -L https://github.com/lh2513/Jun/raw/master/app/src/main/java/com/github/catvod/spider/Xinsj.java > app/src/main/java/com/github/catvod/spider/Xinsj.java
         curl -L https://github.com/lh2513/Jun/raw/master/app/src/main/java/com/github/catvod/spider/YGP.java > app/src/main/java/com/github/catvod/spider/YGP.java
         #sed -i 's/com.github.catvod.utils.okhttp.OkHttpUtil/com.github.catvod.net.OkHttp/g;s/OkHttpUtil/OkHttp/g' app/src/main/java/com/github/catvod/spider/AppYsV2.java
         #curl -L https://github.com/xxxyyy888/CatVodSpider/raw/main/app/src/main/java/com/github/catvod/spider/AppYsV2.java > app/src/main/java/com/github/catvod/spider/AppYsV2.java
        
    - name: Build the app
      working-directory: ./project
      run: |        
         chmod +x gradlew
         ./gradlew assemblerelease --build-cache --parallel --daemon --warning-mode all
         
    - name: Customize Spider Jar
      working-directory: ./project
      run: |        
         rm -rf jar/custom_spider.jar
         rm -rf jar/spider.jar/original/META-INF
         curl -L https://github.com/iBotPeaches/Apktool/releases/download/v2.7.0/apktool_2.7.0.jar > jar/3rd/apktool_2.7.0.jar
         java -jar jar/3rd/baksmali-2.5.2.jar d app/build/intermediates/dex/release/minifyReleaseWithR8/classes.dex -o jar/Smali_classes
         mkdir -p jar/spider.jar/smali/com/github/catvod/
         mv jar/Smali_classes/com/github/catvod/spider jar/spider.jar/smali/com/github/catvod/         
         java -jar jar/3rd/apktool_2.7.0.jar b jar/spider.jar -c
         mv jar/spider.jar/dist/dex.jar ../jar/custom_spider.jar
         md5=($(md5sum ../jar/custom_spider.jar))
         echo $md5 > ../jar/custom_spider.jar.md5
    - name: Upload APK
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Spider
        path: ./jar/custom_spider.jar
